

happy: 
  positions = [
    0.0,
    -3.999999999998449e-05,
    0.06477,
    -0.0016899999999999693,
    -0.0021969999999999603,
    -0.0025199999999999667,
    0.00024000000000001798,
    0.0,
    0.0,
    -0.00010899999999999799,
    -0.0001416999999999974,
    -0.0025199999999999667,
    0.00024000000000001798,
    0.0,
    0.0
  ]
sad:
  positions = [
    0.0,
    0.08408000000000004,
    0.0,
    0.135764,
    0.1764932,
    -0.0014399999999999968,
    0.2168000000000001,
    -0.14544,
    0.3927,
    0.135764,
    0.1764932,
    -0.0014399999999999968,
    0.2168000000000001,
    -0.14544,
    0.325
]
angry:
  positions = [
    0.0,
    -3.999999999998449e-05,
    0.0,
    0.20439800000000002,
    0.26571740000000005,
    -0.005519999999999969,
    0.022719999999999962,
    -0.17272,
    -0.3,
    0.21500000000000002,
    0.2795,
    -0.005519999999999969,
    0.022719999999999962,
    -0.16820000000000002,
    -0.3
]
surprised:
  positions = [
    0.0,
    -3.999999999998449e-05,
    0.19602,
    -0.075625,
    -0.0983125,
    0.0026399999999999757,
    -0.00015999999999993797,
    0.12059999999999998,
    0.4371,
    -0.14956,
    -0.19442800000000002,
    0.0026399999999999757,
    -0.00015999999999993797,
    0.13180000000000003,
    0.45570000000000005
]
sleepy:
  positions = [
    0.0,
    -3.999999999998449e-05,
    0.0,
    0.68,
    0.8840000000000001,
    0.0,
    0.0,
    -0.1092,
    0.15450000000000003,
    0.674699,
    0.8771087000000001,
    0.0,
    0.0,
    -0.11592000000000001,
    0.1886
]
suspicious:
  positions = [
    0.0517399999999999,
    0.02954000000000001,
    0.0,
    0.053924,
    0.07010119999999996,
    0.027240000000000042,
    -0.0009599999999999609,
    0.05584,
    0.1886,
    0.41048600000000013,
    0.5336318000000002,
    0.027240000000000042,
    -0.0009599999999999609,
    -0.14772000000000002,
    -0.3
]
neutral:
  positions = [
    0.0,
    -3.999999999998449e-05,
    0.0,
    -1.6000000000016e-05,
    -2.0800000000020804e-05,
    0.0,
    0.0,
    0.0,
    0.0,
    -1.6000000000016e-05,
    -2.0800000000020804e-05,
    0.0,
    0.0,
    0.0,
    0.0
]

